import * as ts from "typescript/lib/tsserverlibrary";

export default [
	{
		name: "abstract",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "any",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "as",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "asserts",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "async",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "await",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "bigint",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "boolean",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "break",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "case",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "catch",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "class",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "const",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "continue",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "debugger",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "declare",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "default",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "delete",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "do",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "else",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "enum",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "export",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "extends",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "false",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "finally",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "for",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "function",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "if",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "implements",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "import",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "in",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "infer",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "instanceof",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "interface",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "keyof",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "let",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "module",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "namespace",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "never",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "new",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "null",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "number",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "object",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "package",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "readonly",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "return",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "satisfies",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "string",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "super",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "switch",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "symbol",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "this",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "throw",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "true",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "try",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "type",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "typeof",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "unique",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "unknown",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "using",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "var",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "void",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "while",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "with",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "yield",
		kind: "keyword",
		kindModifiers: "",
		sortText: "15",
	},
	{
		name: "mk",
		kind: "const",
		kindModifiers: "export,declare",
		sortText: "16",
		source: "date-fns/locale",
		hasAction: true,
		sourceDisplay: [
			{
				text: "date-fns/locale",
				kind: "text",
			},
		],
		data: {
			exportName: "mk",
			exportMapKey: "2 58497 mk ",
			moduleSpecifier: "date-fns/locale",
			fileName:
				"/app/node_modules/.pnpm/date-fns@3.6.0/node_modules/date-fns/locale.d.mts",
		},
	},
	{
		name: "mk",
		kind: "alias",
		kindModifiers: "declare",
		sortText: "16",
		source: "@faker-js/faker",
		hasAction: true,
		sourceDisplay: [
			{
				text: "@faker-js/faker",
				kind: "text",
			},
		],
		data: {
			exportName: "mk",
			exportMapKey: "2 60165 mk ",
			moduleSpecifier: "@faker-js/faker",
			fileName:
				"/app/node_modules/.pnpm/@faker-js+faker@8.4.1/node_modules/@faker-js/faker/dist/types/index.d.ts",
		},
	},
	{
		name: "mk",
		kind: "const",
		kindModifiers: "export,declare",
		sortText: "16",
		source: "date-fns/locale/mk",
		hasAction: true,
		sourceDisplay: [
			{
				text: "date-fns/locale/mk",
				kind: "text",
			},
		],
		isPackageJsonImport: true,
		data: {
			exportName: "mk",
			exportMapKey: "2 72592 mk ",
			moduleSpecifier: "date-fns/locale/mk",
			fileName:
				"/app/node_modules/.pnpm/date-fns@3.6.0/node_modules/date-fns/locale/mk.d.mts",
			isPackageJsonImport: true,
		},
	},
	{
		name: "mkdir",
		kind: "function",
		kindModifiers: "export,declare",
		sortText: "16",
		source: "node:fs",
		hasAction: true,
		sourceDisplay: [
			{
				text: "node:fs",
				kind: "text",
			},
		],
		data: {
			exportName: "mkdir",
			exportMapKey: "5 33234 mkdir node:fs",
			moduleSpecifier: "node:fs",
			ambientModuleName: "node:fs",
		},
	},
	{
		name: "mkdir",
		kind: "function",
		kindModifiers: "declare",
		sortText: "16",
		source: "node:fs/promises",
		hasAction: true,
		sourceDisplay: [
			{
				text: "node:fs/promises",
				kind: "text",
			},
		],
		data: {
			exportName: "mkdir",
			exportMapKey: "5 33343 mkdir node:fs/promises",
			moduleSpecifier: "node:fs/promises",
			ambientModuleName: "node:fs/promises",
		},
	},
	{
		name: "mkdirSync",
		kind: "function",
		kindModifiers: "export,declare",
		sortText: "16",
		source: "node:fs",
		hasAction: true,
		sourceDisplay: [
			{
				text: "node:fs",
				kind: "text",
			},
		],
		data: {
			exportName: "mkdirSync",
			exportMapKey: "9 33235 mkdirSync node:fs",
			moduleSpecifier: "node:fs",
			ambientModuleName: "node:fs",
		},
	},
	{
		name: "mkdtemp",
		kind: "function",
		kindModifiers: "export,declare",
		sortText: "16",
		source: "node:fs",
		hasAction: true,
		sourceDisplay: [
			{
				text: "node:fs",
				kind: "text",
			},
		],
		data: {
			exportName: "mkdtemp",
			exportMapKey: "7 33236 mkdtemp node:fs",
			moduleSpecifier: "node:fs",
			ambientModuleName: "node:fs",
		},
	},
	{
		name: "mkdtemp",
		kind: "function",
		kindModifiers: "declare",
		sortText: "16",
		source: "node:fs/promises",
		hasAction: true,
		sourceDisplay: [
			{
				text: "node:fs/promises",
				kind: "text",
			},
		],
		data: {
			exportName: "mkdtemp",
			exportMapKey: "7 33359 mkdtemp node:fs/promises",
			moduleSpecifier: "node:fs/promises",
			ambientModuleName: "node:fs/promises",
		},
	},
	{
		name: "mkdtempSync",
		kind: "function",
		kindModifiers: "export,declare",
		sortText: "16",
		source: "node:fs",
		hasAction: true,
		sourceDisplay: [
			{
				text: "node:fs",
				kind: "text",
			},
		],
		data: {
			exportName: "mkdtempSync",
			exportMapKey: "11 33237 mkdtempSync node:fs",
			moduleSpecifier: "node:fs",
			ambientModuleName: "node:fs",
		},
	},
] as ts.CompletionEntry[];
